services:
  drivers-express:
    container_name: drivers-express
    image: sarmadparvez/drivers-express
    ports:
      - 3333:3333
  angular-drivers:
    container_name: angular-drivers
    image: sarmadparvez/angular-drivers
    ports:
      - 4200:80
